<div id="p1" class="FURORE page">
<a href="" ><div id="CmagazinePhoto" style="background-image:url('../Furore/Images/issue2.jpg')"></div></a>
<div id="magazineInfo">
	<h2 class='magazineHead' id='currentHead'>SCHRODINGER'S HAT</h2><div class='magazineText' id='currentText'>
		Issue #2<br>Release Date : 31<sup>st</sup> August 2013<p>Is the cat dead or alive? If Schrodinger's cat could cause all this buzz, imagine what the inside of Schrodinger's head would feel like.  Take a peep inside Schrodinger's hat, where science gets wacky and fact is stranger than fiction. Dwelling into the unexplored realms of science fiction, the second edition of Furore gives you a peak into a futuristic world of time travel, intelligent humanoids and extra terrestrial life...</p>
		Click <a href='http://www.thefishbowlnetwork.com/furore/issue2.php'><i>here</i></a> to read the magazine
	</div>
	<h2 class='magazineHead'>THE ART OF START</h2><div class='magazineText'>
		Issue #1<br>Release Date : 26<sup>th</sup> June 2013<p>Tune into the first edition of our magazine: "The Art of Start" for inspiration. When was the last time you did something different for the first time? want to get going and get your hands dirty doing something unique? Then waste no time in checking it out! Themed upon how innovations are born in different walks of life, the pioneering developments are sure to leave you stimulated, dreaming about your own start..</p>
		Click <a href='http://www.thefishbowlnetwork.com/furore1/issue.php'><i>here</i></a> to read the magazine
	</div>
	<h2 class='magazineHead'>FURORE</h2><div class='magazineText'>Furore is The Fishbowl Network's bimonthly magazine, focusing on an eclectic mix of topics. Each magazine is themed, and is sure to keep you gripped with the assorted content generated by our cretive team. </div></div>
<div id="magazineSlider"><div data-number='0'class="magazineThumbnail" style="background-image:url('../Furore/Images/issue2.jpg')"></div><div data-number='1' class="magazineThumbnail" style="background-image:url('../Furore/Images/issue1.jpg')"></div><div data-number='2' class="magazineThumbnail" style="background-image:url('../Furore/Images/30.jpg')"></div></div>
</div>